### ISSUE TITLE
write readme

### ISSUE THREAD

**Issue by PietrH** [inbo/etnservice#4]
The readme should include a description of what this repo/package is, how to use the api (refer to etn, but also short examples on how to make curl/httr requests), needed credentials to use the service and maintenance information. 

It would also be nice to setup github actions for testing, and have some badges on the readme.

**Comment by peterdesmet** [comment]
If we want to include examples, I would opt for a `README.Rmd` (that is translated by `devtools::build_readme()` to a .md). Use `usethis::use_readme_rmd()` to initalize this.

**Comment by PietrH** [comment]
Implemented in #1
